package amazon.db.model;

import java.util.Date;

public class ListOrdersTrack {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_orders_track.id
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_orders_track.created_before
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    private Date createdBefore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_orders_track.status
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_orders_track.start_time
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_orders_track.end_time
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_orders_track.id
     *
     * @return the value of list_orders_track.id
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_orders_track.id
     *
     * @param id the value for list_orders_track.id
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_orders_track.created_before
     *
     * @return the value of list_orders_track.created_before
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public Date getCreatedBefore() {
        return createdBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_orders_track.created_before
     *
     * @param createdBefore the value for list_orders_track.created_before
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public void setCreatedBefore(Date createdBefore) {
        this.createdBefore = createdBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_orders_track.status
     *
     * @return the value of list_orders_track.status
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_orders_track.status
     *
     * @param status the value for list_orders_track.status
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_orders_track.start_time
     *
     * @return the value of list_orders_track.start_time
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_orders_track.start_time
     *
     * @param startTime the value for list_orders_track.start_time
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_orders_track.end_time
     *
     * @return the value of list_orders_track.end_time
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_orders_track.end_time
     *
     * @param endTime the value for list_orders_track.end_time
     *
     * @mbg.generated Thu Jul 27 22:08:47 CST 2017
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}