package amazon.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class Orders {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.amazon_order_id
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String amazonOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.seller_order_id
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String sellerOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.purchase_date
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private Date purchaseDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.last_update_date
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private Date lastUpdateDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.sales_channel
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String salesChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.fulfillment_channel
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String fulfillmentChannel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.is_business_order
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String isBusinessOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.is_premium_order
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String isPremiumOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.is_prime
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String isPrime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.buyer_name
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String buyerName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.buyer_email
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String buyerEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.order_status
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.order_total_currency
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String orderTotalCurrency;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.order_total_amount
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private BigDecimal orderTotalAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.ship_service_category
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String shipServiceCategory;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.ship_service_level
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private String shipServiceLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.number_items_shipped
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private Integer numberItemsShipped;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column orders.number_items_unshipped
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	private Integer numberItemsUnshipped;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.amazon_order_id
	 * @return  the value of orders.amazon_order_id
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getAmazonOrderId() {
		return amazonOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.amazon_order_id
	 * @param amazonOrderId  the value for orders.amazon_order_id
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setAmazonOrderId(String amazonOrderId) {
		this.amazonOrderId = amazonOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.seller_order_id
	 * @return  the value of orders.seller_order_id
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getSellerOrderId() {
		return sellerOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.seller_order_id
	 * @param sellerOrderId  the value for orders.seller_order_id
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setSellerOrderId(String sellerOrderId) {
		this.sellerOrderId = sellerOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.purchase_date
	 * @return  the value of orders.purchase_date
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public Date getPurchaseDate() {
		return purchaseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.purchase_date
	 * @param purchaseDate  the value for orders.purchase_date
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setPurchaseDate(Date purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.last_update_date
	 * @return  the value of orders.last_update_date
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public Date getLastUpdateDate() {
		return lastUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.last_update_date
	 * @param lastUpdateDate  the value for orders.last_update_date
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setLastUpdateDate(Date lastUpdateDate) {
		this.lastUpdateDate = lastUpdateDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.sales_channel
	 * @return  the value of orders.sales_channel
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getSalesChannel() {
		return salesChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.sales_channel
	 * @param salesChannel  the value for orders.sales_channel
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setSalesChannel(String salesChannel) {
		this.salesChannel = salesChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.fulfillment_channel
	 * @return  the value of orders.fulfillment_channel
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getFulfillmentChannel() {
		return fulfillmentChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.fulfillment_channel
	 * @param fulfillmentChannel  the value for orders.fulfillment_channel
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setFulfillmentChannel(String fulfillmentChannel) {
		this.fulfillmentChannel = fulfillmentChannel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.is_business_order
	 * @return  the value of orders.is_business_order
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getIsBusinessOrder() {
		return isBusinessOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.is_business_order
	 * @param isBusinessOrder  the value for orders.is_business_order
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setIsBusinessOrder(String isBusinessOrder) {
		this.isBusinessOrder = isBusinessOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.is_premium_order
	 * @return  the value of orders.is_premium_order
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getIsPremiumOrder() {
		return isPremiumOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.is_premium_order
	 * @param isPremiumOrder  the value for orders.is_premium_order
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setIsPremiumOrder(String isPremiumOrder) {
		this.isPremiumOrder = isPremiumOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.is_prime
	 * @return  the value of orders.is_prime
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getIsPrime() {
		return isPrime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.is_prime
	 * @param isPrime  the value for orders.is_prime
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setIsPrime(String isPrime) {
		this.isPrime = isPrime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.buyer_name
	 * @return  the value of orders.buyer_name
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getBuyerName() {
		return buyerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.buyer_name
	 * @param buyerName  the value for orders.buyer_name
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setBuyerName(String buyerName) {
		this.buyerName = buyerName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.buyer_email
	 * @return  the value of orders.buyer_email
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getBuyerEmail() {
		return buyerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.buyer_email
	 * @param buyerEmail  the value for orders.buyer_email
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setBuyerEmail(String buyerEmail) {
		this.buyerEmail = buyerEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.order_status
	 * @return  the value of orders.order_status
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.order_status
	 * @param orderStatus  the value for orders.order_status
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.order_total_currency
	 * @return  the value of orders.order_total_currency
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getOrderTotalCurrency() {
		return orderTotalCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.order_total_currency
	 * @param orderTotalCurrency  the value for orders.order_total_currency
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setOrderTotalCurrency(String orderTotalCurrency) {
		this.orderTotalCurrency = orderTotalCurrency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.order_total_amount
	 * @return  the value of orders.order_total_amount
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public BigDecimal getOrderTotalAmount() {
		return orderTotalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.order_total_amount
	 * @param orderTotalAmount  the value for orders.order_total_amount
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setOrderTotalAmount(BigDecimal orderTotalAmount) {
		this.orderTotalAmount = orderTotalAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.ship_service_category
	 * @return  the value of orders.ship_service_category
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getShipServiceCategory() {
		return shipServiceCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.ship_service_category
	 * @param shipServiceCategory  the value for orders.ship_service_category
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setShipServiceCategory(String shipServiceCategory) {
		this.shipServiceCategory = shipServiceCategory;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.ship_service_level
	 * @return  the value of orders.ship_service_level
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public String getShipServiceLevel() {
		return shipServiceLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.ship_service_level
	 * @param shipServiceLevel  the value for orders.ship_service_level
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setShipServiceLevel(String shipServiceLevel) {
		this.shipServiceLevel = shipServiceLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.number_items_shipped
	 * @return  the value of orders.number_items_shipped
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public Integer getNumberItemsShipped() {
		return numberItemsShipped;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.number_items_shipped
	 * @param numberItemsShipped  the value for orders.number_items_shipped
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setNumberItemsShipped(Integer numberItemsShipped) {
		this.numberItemsShipped = numberItemsShipped;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column orders.number_items_unshipped
	 * @return  the value of orders.number_items_unshipped
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public Integer getNumberItemsUnshipped() {
		return numberItemsUnshipped;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column orders.number_items_unshipped
	 * @param numberItemsUnshipped  the value for orders.number_items_unshipped
	 * @mbg.generated  Fri Feb 24 15:46:14 CST 2017
	 */
	public void setNumberItemsUnshipped(Integer numberItemsUnshipped) {
		this.numberItemsUnshipped = numberItemsUnshipped;
	}
}