package internal.db.model;

import java.util.Date;

public class InternalProduct {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column internal_product.product_id
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column internal_product.name
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column internal_product.description
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column internal_product.create_time
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column internal_product.status
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column internal_product.asin
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	private String asin;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column internal_product.product_id
	 * @return  the value of internal_product.product_id
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column internal_product.product_id
	 * @param productId  the value for internal_product.product_id
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column internal_product.name
	 * @return  the value of internal_product.name
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column internal_product.name
	 * @param name  the value for internal_product.name
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column internal_product.description
	 * @return  the value of internal_product.description
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column internal_product.description
	 * @param description  the value for internal_product.description
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column internal_product.create_time
	 * @return  the value of internal_product.create_time
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column internal_product.create_time
	 * @param createTime  the value for internal_product.create_time
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column internal_product.status
	 * @return  the value of internal_product.status
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column internal_product.status
	 * @param status  the value for internal_product.status
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column internal_product.asin
	 * @return  the value of internal_product.asin
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public String getAsin() {
		return asin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column internal_product.asin
	 * @param asin  the value for internal_product.asin
	 * @mbg.generated  Mon Mar 20 12:44:13 CST 2017
	 */
	public void setAsin(String asin) {
		this.asin = asin;
	}
}