package internal.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class ProductSupply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.supply_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private Integer supplyId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.product_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.supplier_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private Integer supplierId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.supplier_name
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private String supplierName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.supplier_description
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private String supplierDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.supply_type
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private String supplyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.supply_url
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private String supplyUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.shipped_from
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private String shippedFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.unit_price
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private BigDecimal unitPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.price_description
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private String priceDescription;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.price_time
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private Date priceTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_supply.status
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	private String status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.supply_id
	 * @return  the value of product_supply.supply_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public Integer getSupplyId() {
		return supplyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.supply_id
	 * @param supplyId  the value for product_supply.supply_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setSupplyId(Integer supplyId) {
		this.supplyId = supplyId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.product_id
	 * @return  the value of product_supply.product_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.product_id
	 * @param productId  the value for product_supply.product_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.supplier_id
	 * @return  the value of product_supply.supplier_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public Integer getSupplierId() {
		return supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.supplier_id
	 * @param supplierId  the value for product_supply.supplier_id
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setSupplierId(Integer supplierId) {
		this.supplierId = supplierId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.supplier_name
	 * @return  the value of product_supply.supplier_name
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public String getSupplierName() {
		return supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.supplier_name
	 * @param supplierName  the value for product_supply.supplier_name
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setSupplierName(String supplierName) {
		this.supplierName = supplierName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.supplier_description
	 * @return  the value of product_supply.supplier_description
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public String getSupplierDescription() {
		return supplierDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.supplier_description
	 * @param supplierDescription  the value for product_supply.supplier_description
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setSupplierDescription(String supplierDescription) {
		this.supplierDescription = supplierDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.supply_type
	 * @return  the value of product_supply.supply_type
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public String getSupplyType() {
		return supplyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.supply_type
	 * @param supplyType  the value for product_supply.supply_type
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setSupplyType(String supplyType) {
		this.supplyType = supplyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.supply_url
	 * @return  the value of product_supply.supply_url
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public String getSupplyUrl() {
		return supplyUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.supply_url
	 * @param supplyUrl  the value for product_supply.supply_url
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setSupplyUrl(String supplyUrl) {
		this.supplyUrl = supplyUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.shipped_from
	 * @return  the value of product_supply.shipped_from
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public String getShippedFrom() {
		return shippedFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.shipped_from
	 * @param shippedFrom  the value for product_supply.shipped_from
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setShippedFrom(String shippedFrom) {
		this.shippedFrom = shippedFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.unit_price
	 * @return  the value of product_supply.unit_price
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public BigDecimal getUnitPrice() {
		return unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.unit_price
	 * @param unitPrice  the value for product_supply.unit_price
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.price_description
	 * @return  the value of product_supply.price_description
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public String getPriceDescription() {
		return priceDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.price_description
	 * @param priceDescription  the value for product_supply.price_description
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setPriceDescription(String priceDescription) {
		this.priceDescription = priceDescription;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.price_time
	 * @return  the value of product_supply.price_time
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public Date getPriceTime() {
		return priceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.price_time
	 * @param priceTime  the value for product_supply.price_time
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setPriceTime(Date priceTime) {
		this.priceTime = priceTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_supply.status
	 * @return  the value of product_supply.status
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_supply.status
	 * @param status  the value for product_supply.status
	 * @mbg.generated  Wed Jul 12 10:05:27 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}
}